# https://jekyllrb.com/docs/configuration/

permalink: /posts/:title/
baseurl: ""
# paginate: 5
url: "http://cppcho.com"
timezone: UTC
strict_front_matter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tasks/
  - README.md
  - yarn-error.log
  - yarn.lock
  - package.json
  - Rakefile
  - LICENSE

plugins:
  - jekyll-seo-tag

title: Patrick Cho
description: Hi! I am a software developer from Hong Kong, and this is my personal website.
url: http://cppcho.com
author: Patrick Cho

# Custom vars
email: cppcho.hk@gmail.com
github_username: cppcho
linkedin_username: cppcho
google_analytics: UA-110940483-1

header_pages:
# - about.md
