# https://jekyllrb.com/docs/configuration/

permalink: /posts/:title/
baseurl: ""
# paginate: 5
url: "http://cppcho.com"
timezone: UTC
strict_front_matter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Custom vars
title: Patrick Cho
email: cppcho.hk@gmail.com
github_username: cppcho
linkedin_username: cppcho

header_pages:
# - about.md
